title: Vernon Lam
logo: /assets/img/headshot.jpeg
description: Data Professional with experience in marketing, research and government. Studying Master's Degree in Data Science from UNSW, expected graduation April 2024.
<a href ="https://www.linkedin.com/in/vernon-lam-776b59238/">View my LinkedIn Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
