title: Vernon Lam
logo: /assets/img/headshot.png
description: Data Professional with experience in marketing, research and government. Studying Master's Degree in Data Science from UNSW, expected graduation April 2024.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
